# Simple Vedic astrology calculation stubs
from datetime import datetime
import math

def sun_sign_from_birth(dt: datetime, lat: float = 0.0, lon: float = 0.0) -> str:
    '''
    VERY simple stub: returns a zodiac sign based on month only.
    Replace with actual sidereal calculations for production.
    '''
    month = dt.month
    signs = ["Capricorn","Aquarius","Pisces","Aries","Taurus","Gemini",
             "Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius"]
    return signs[(month - 1) % 12]

def sample_chart(name: str, birth_iso: str, lat: float, lon: float):
    dt = datetime.fromisoformat(birth_iso)
    return {
        "name": name,
        "birth": birth_iso,
        "lat": lat,
        "lon": lon,
        "sun_sign": sun_sign_from_birth(dt, lat, lon),
        "note": "This is a demo chart generated by the Vedic blueprint. Replace with real calculations."
    }
